qwizkoolweb/quiz/urls.py
from django.urls import path

from . import views

# app namespace to avoid conflict with other apps
app_name = 'quiz'

urlpatterns = [
    # ex: /quiz/
    path('', views.IndexView.as_view(), name='index'),
    # ex: /quiz/create_quiz
    path('create_quiz/', views.create_quiz, name='create_quiz'),
    # ex: /quiz/5/
    path('<int:quiz_id>/', views.QuizDetailView.as_view(), name='quiz_detail'),
    # ex: /quiz/5/get_status
    path('<int:quiz_id>/get_status', views.get_status, name='get_status'),
    # ex: /quiz/5/results/
    path('<int:quiz_id>/results/', views.QuizResultsView.as_view(), name='quiz_results'),
    # ex: /quiz/5/question/5/
    path('<int:quiz_id>/question/<int:question_id>/', views.QuestionView.as_view(), name='question'),
    # ex: /quiz/5/question/5/check_answer
    path('<int:quiz_id>/question/<int:question_id>/check_answer', views.check_answer, name='check_answer'),
    # ex: /quiz/5/question/5/results
    path('<int:quiz_id>/question/<int:question_id>/choice/<int:choice_id>/results/', views.QuestionResultsView.as_view(), name='question_results'),
]

qwizkoolweb/qwizkoolweb/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('quiz/', include('quiz.urls')),
    path('admin/', admin.site.urls),
]

qwizkoolweb/quiz/models.py
# Create your models here.
import datetime
from django.db import models
from django.utils import timezone

class Quiz(models.Model):
    title_text = models.CharField(max_length=80)    
    description_text = models.CharField(max_length=800)
    pub_date = models.DateTimeField(verbose_name='date published', auto_now_add=True, blank=True)
    status_text = models.CharField(default='Initializing', max_length=80)
    status_detail_text = models.CharField(default='Initializing', max_length=160)
    question_count = models.IntegerField(default=0)
    question_count_max = models.IntegerField(default=0)
    first_question_id = models.IntegerField(default=0)
    author = models.CharField(default='unknown', max_length=80)
    
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def get_num_attempted(self):
        total = 0
        attempted = 0
        correct = 0
        wrong = 0

        for q in self.question_set.all():
            total += 1
            if q.attempted:
                attempted += 1
                if q.passed:
                    correct += 1
                else:
                    wrong += 1    
        return attempted          

    def __str__(self):
        return self.title_text

class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    question_text = models.CharField(max_length=320)
    attempted = models.BooleanField(default=False)
    passed = models.BooleanField(default=False)

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return self.choice_text

qwizkoolweb/quiz/views.py
from django.shortcuts import get_object_or_404, render

# Create your views here.
from django.http import Http404
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse

from django.urls import reverse
from django.views import generic
from django.forms.models import model_to_dict

from .models import Choice, Question, Quiz
from .tasks import QuizCreator
from .tasks import quiz_create_bg
import time
import sys
import threading


class IndexView(generic.ListView):
    template_name = 'index.html'
    context_object_name = 'latest_quiz_list'

    def get_queryset(self):

        """WARNING !!!! WARNING !!!! WARNING !!!!! """
        """ Deleting all older quizzes to keep the db small"""        
        """ Remove for production"""                
        quiz_list = Quiz.objects.order_by('-pub_date')[15:]
        for quiz in quiz_list:
            quiz.delete()

        # Delete any failed entries
        quiz_list = Quiz.objects.order_by('-pub_date')
        for quiz in quiz_list:
            if quiz.status_text == 'FAILED':
                quiz.delete()

        """Return the last five published questions."""
        return Quiz.objects.order_by('-pub_date')[:5]


def create_quiz(request):

    topic = request.POST.get('topic')
    quiz = Quiz.objects.create(title_text=topic)
    quiz.save()

    t = threading.Thread(target=QuizCreator().startGPT, args=[quiz.id])
    t.setDaemon(True)
    t.start()

    # When using with background tasks
    #quiz_create_bg(quiz.id)


    context = {
        'topic': topic, 
        'quiz_id': quiz.id,      
        'first_question_id' : 1  # Will be replaced in the template code
        }   

    return render(request, 'create_quiz_progress.html', context)  


def create_quiz_old(request):
    topic = request.POST.get('topic')

    quiz_id = QuizCreator().start(topic)
    quiz = get_object_or_404(Quiz, pk=quiz_id)
    if quiz.status_text == 'READY':
        first_question = list(quiz.question_set.all())[0] 
        context = {
            'topic': topic, 
            'quiz_id': quiz_id,
            'description' : quiz.description_text,
            'information' : "The Quiz has " + str(quiz.question_count_max) + " questions.",
            'question' : first_question               
            }

        return render(request, 'create_quiz_progress.html', context)  
    else:    
        e_str_html = quiz.status_detail_text.replace("\n", "<br />") 
        context = {
            'topic': topic, 
            'information': e_str_html,
        }
        quiz.delete()
        return render(request, 'create_quiz_fail.html', context)    

# Retained for showing example usage with HttpResponse
# def detail(request, question_id):
#    return HttpResponse("You're looking at question %s." % question_id)

# Retained for showing example of geneting custom 404
# def detail(request, question_id):
#    try:
#        question = Question.objects.get(pk=question_id)
#    except Question.DoesNotExist:
#        raise Http404("Question does not exist")
#    return render(request, 'detail.html', {'question': question})


class QuizDetailView(generic.TemplateView):
    template_name = 'quiz_detail.html'
    
    def get_context_data(self, **kwargs):
        
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)

        # Add to the template context
        quiz_id = self.kwargs['quiz_id'] 
        quiz = get_object_or_404(Quiz, pk=quiz_id)

        # Clear attemped flags
        for q in quiz.question_set.all():
            q.attempted = False
            q.save()
        
        first_question = list(quiz.question_set.all())[0]             

        context['quiz'] =  quiz
        context['question'] = first_question
        return context 


class QuestionView(generic.TemplateView):
    template_name = 'question.html'
    
    def get_context_data(self, **kwargs):
        
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)

        # Add to the template context
        quiz_id = self.kwargs['quiz_id'] 
        question_id = self.kwargs['question_id']   
        quiz = get_object_or_404(Quiz, pk=quiz_id)
   
        context['question'] =  get_object_or_404(Question, pk=question_id)
        context['question_number'] = quiz.get_num_attempted() + 1        
        return context  

class QuizResultsView(generic.TemplateView):
    template_name = 'quiz_results.html'
    
    def get_context_data(self, **kwargs):
        
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)

        # Add to the template context
        quiz_id = self.kwargs['quiz_id'] 
        quiz = get_object_or_404(Quiz, pk=quiz_id)

        total = 0
        attempted = 0
        correct = 0
        wrong = 0

        for q in quiz.question_set.all():
            total += 1
            if q.attempted:
                attempted += 1
                if q.passed:
                    correct += 1
                else:
                    wrong += 1    
            
        context.update({
            'quiz': quiz,
            'total':total,
            'attempted':attempted,
            'correct' : correct,
            'wrong':wrong,
            })            

        return context 

class QuestionResultsView(generic.TemplateView):
    template_name = 'question_results.html'
    
    def get_context_data(self, **kwargs):
        
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)

        # Add to the template context
        choice_id = self.kwargs['choice_id'] 
        question_id = self.kwargs['question_id']  

        context['question'] =  get_object_or_404(Question, pk=question_id)
        context['choice'] = get_object_or_404(Choice, pk=choice_id)        
        return context        


# Get status of quiz creation
def get_status(request, quiz_id):
    quiz = get_object_or_404(Quiz, pk=quiz_id)
    return JsonResponse(model_to_dict(quiz))


# Choice id arrives in the POST request
def check_answer(request, quiz_id, question_id):
    question = get_object_or_404(Question, pk=question_id)
    quiz = get_object_or_404(Quiz, pk=quiz_id)

    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question form.
        return render(request, 'question.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
            'question_number' : quiz.get_num_attempted() + 1
        })

    question.attempted = True    
    if selected_choice.is_correct:
        message = selected_choice.choice_text + " is the correct answer!"
        question.passed = True
    else:    
        for choice in question.choice_set.all():
            if choice.is_correct:
                correct_choice = choice
        
        message = selected_choice.choice_text + " is the wrong answer! Correct answer is " + correct_choice.choice_text 
        question.passed = False

    question.save()

    # Get the next question
    next_question = None
    for q in question.quiz.question_set.all():
        if not q.attempted:
            next_question = q
            break

    return render(request, 'question_results.html', {
        'question': question,
        'passed' : question.passed, 
        'result_message': message,
        'next_question' : next_question,
    })        
      

qwizkoolweb/quiz/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>

    <head>
        <title>K.N.O.E.B</title>
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
        <meta name="google" content="notranslate" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
            crossorigin="anonymous" />
    </head>

    <body>
        <style>
            body {
            font-family: "Roboto", sans-serif;
            font-size: 14px;
            background-color: #fdfdfd;
        }
        .shadow {
            box-shadow: 0 4px 2px -2px rgba(0, 0, 0, 0.1);
        }
        .btn-danger {
            color: #fff;
            background-color: #f00000;
            border-color: #dc281e;
        }
        .masthead {
            background: #3398E1;
            height: auto;
            padding-bottom: 15px;
            box-shadow: 0 16px 48px #E3E7EB;
            padding-top: 10px;
        }
    </style>

        <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light shadow" id="mainNav">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'quiz:index' %}"><img src="{% static 'img/home.png' %}" alt="Go Home" style="width:42px;height:42px;"></a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="#">Login</a>
                        </li>
                        <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="#">Resources</a>
                        </li>
                        <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="#">Contact</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}

        <!-- Footer -->
        <footer class="py-3 bg-grey">
            <p class="m-0 text-dark text-center ">Copyright &copy; K.N.O.E.B</p>
        </footer>
    </body>
</html>

qwizkoolweb/quiz/templates/bootstrap.html
{% extends 'bootstrap4/bootstrap4.html' %}
{% load bootstrap4 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

qwizkoolweb/quiz/templates/create_quiz_fail.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}
<div class="container">


<p><h4>Failed to create Quiz for topic {{ topic }}</h4></p>
<p><h6>{{ information|safe }}</h6></p>

<form action="{% url 'quiz:index' %}" method="get">
    {% csrf_token %}
    {% buttons %}
    <button type="submit" class="btn btn-primary">Go Home</button>
    {% endbuttons %}      
</form>

</div>
{% endblock %}

qwizkoolweb/quiz/templates/create_quiz_progress.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}
<div class="container">

<p><h4><div id="headline"></div></h4></p>
<p><h5><em><div id="description"></div></em></h5></h5></p>
<p id="status_block">
    <strong><span id="status"></span></strong>
    <progress style="visibility:visible" id="progress" value="0" max="100"></progress>
    <strong><span id="prog_value"></span></strong>    
    <strong><span id="prog_max"></span></strong>        
</p>
<p><h5><div id="result"></div></h5></p>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="text/javascript">
    var progress_value = 0;
    var status_text = '';

    var itimer = setInterval(function() { 
        var status_url = "{% url 'quiz:get_status' quiz_id %}";
        $.getJSON(status_url, function(jd) {
                  $('#headline').html("Creating Quiz for " + jd.title_text);
                  $('#status').html(jd.status_text);
                  $('#description').html(jd.description_text);    

                  if (jd.status_text != status_text ) {
                    progress_value = 0;
                    status_text = jd.status_text;
                  }

                  if (jd.question_count_max > 0) {
                    $('#progress').attr("style", "visibility:visible"); 
                    $('#progress').attr("max", jd.question_count_max); 
                    $('#progress').attr("value", jd.question_count); 
                    $('#prog_max').html(jd.question_count_max); 
                    $('#prog_value').html(jd.question_count + "/"); 
                  } else {
                    $('#progress').attr("value", progress_value++);  
                  } 
                  
                  if (jd.status_text == 'READY') {
                    clearInterval(itimer);
                    //window.location.replace('/quiz');
                    $('#headline').html("Created Quiz for " + jd.title_text);
                    $('#status_block').attr("style", "visibility:hidden");
                    $('#description').attr("style", "visibility:visible");  
                    $('#progress').attr("style", "display:none"); 
                    $('#result').html("The Quiz has " + jd.question_count_max + " questions.");
                    
                    var url = "{% url 'quiz:question' quiz_id first_question_id %}";
                    //console.log(url);
                    var new_url = url.replace("question/" + "{{ first_question_id }}", "question/" + jd.first_question_id);
                    //console.log(new_url);

                    $('#start_button').attr("action", new_url);    
                    $('#start_button').attr("style", "display:inline");    
                }
                
                if (jd.status_text == 'FAILED') {
                    clearInterval(itimer);
                    //window.location.replace('/quiz');
                    $('#headline').html("Failed to create Quiz for topic " + jd.title_text);
                    $('#status').attr("style", "visibility:hidden");
                    $('#result').html(jd.status_detail_text);
                    $('#progress').attr("style", "display:none"); 
                    $('#home_button').attr("style", "display:inline");    
                }

               });

    }, 1000);

</script>

<form id="start_button" style="display:none" action="{% url 'quiz:question' quiz_id first_question_id %}" method="get">
    {% csrf_token %}
    {% buttons %}
    <button type="submit" class="btn btn-primary">Start Quiz</button>
    {% endbuttons %}      
</form>

<form id="home_button" style="display:none" action="{% url 'quiz:index' %}" method="get">
    {% csrf_token %}
    {% buttons %}
    <button type="submit" class="btn btn-primary">Go Home</button>
    {% endbuttons %}      
</form>

</div>
{% endblock %}    

qwizkoolweb/quiz/templates/create_quiz_success.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}
<div class="container">

<p><h4>Created Quiz for {{ topic }}</h4></p>
<p><h5><em>{{ description }}</em></h5></h5></p>
<p><h5>{{ information }}</h5></p>

<form action="{% url 'quiz:question' question.quiz.id question.id %}" method="get">
    {% csrf_token %}
    {% buttons %}
    <button type="submit" class="btn btn-primary">Start Quiz</button>
    {% endbuttons %}      
    </form>


</div>
{% endblock %}    

qwizkoolweb/quiz/templates/index.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}
<style>
    body {
        font-family: "Roboto", sans-serif;
        font-size: 15px;
        background-color: #fdfdfd;
    }

    .head_text {
        color: white;
    }

    .card {
        box-shadow: 0 16px 48px #E3E7EB;
    }
</style>

<header class="masthead">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class=" col-md-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h3 class=" site-heading my-4 mt-3 text-white"> Smart Quiz Generator </h3>
                    <p class="text-light">The art and science of asking questions is the source of all knowledge. -Thomas Berger &nbsp
                    </p>
                </div>
            </div>
        </div>
    </div>
</header>
<div class="container">
    <div class="row">

        <!-- Blog Create Column -->
        <div class="col-md-8 mt-3 left">
            <div class="card mb-4">
                <div class="card-body">
                    <h4 class="card-title">Create New Quiz</h4>
                    <form action="{% url 'quiz:create_quiz' %}" method="post">
                        {% csrf_token %}
                        <label for="topic">Topic keywords: </label>
                        <input id="topic" type="text" name="topic" value="{{ topic_text }}">
                        {% buttons %}
                            <button type="submit" class="btn btn-primary">Go!</button>
                        {% endbuttons %}
                    </form> 
                </div>
            </div>
        </div>

        {% block sidebar %} {% include 'sidebar.html' %} {% endblock sidebar %}

        <!-- Blog Entries Column -->
        <div class="col-md-8 mt-3 left">
            {% for quiz in latest_quiz_list %}
            <div class="card mb-4">
                <div class="card-body">
                    <h5 class="card-title">{{ quiz.title_text }}</h5>
                    <p class="card-text text-muted h6">{{ quiz.author }} | {{ quiz.pub_date}} </p>
                    <p class="card-text">{{quiz.description_text|slice:":200" }}</p>
                    <a href="{% url 'quiz:quiz_detail' quiz.id %}" class="btn btn-primary">Take this quiz &rarr;</a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{%endblock%}

qwizkoolweb/quiz/templates/old_index.html
{% extends 'quiz/bootstrap.html' %}
{% load bootstrap4 %}

{% block bootstrap4_content %}
<div class="container">

<p><h4>Available quizzes</h4></p>
{% if latest_quiz_list %}
    <ul>
    {% for quiz in latest_quiz_list %}
        {# COMMENT <li><a href="/quiz/{{ question.id }}/">{{ question.question_text }}</a></li> HARD CODED URL #}
        {# COMMENT <li><a href="{% url 'detail' question.id %}">{{ question.question_text }}</a></li> WITHOUT NAME SPACE #}
        <li><a href="{% url 'quiz:quiz_detail' quiz.id %}">{{ quiz.title_text }}</a></li> {# COMMENT : WITH quiz namespace defined in url.py #}
    {% endfor %}
    </ul>
{% else %}
    <p>No quizzes are available.</p>
{% endif %}

<p><h4>Create new quiz</h4></p>
<form action="{% url 'quiz:create_quiz' %}" method="post">
    {% csrf_token %}
    <label for="topic">Topic keywords: </label>
    <input id="topic" type="text" name="topic" value="{{ topic_text }}">
    {% buttons %}
        <button type="submit" class="btn btn-primary">Submit</button>
    {% endbuttons %}
</form> 

</div>
{% endblock %}

qwizkoolweb/quiz/templates/question.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}
<div class="container">

<p><h5>{{question_number}}. {{ question.question_text }}</h5></p>

{% if error_message %}<strong><p class="text-danger">{{ error_message }}</p></strong>{% endif %}

<form action="{% url 'quiz:check_answer' question.quiz.id question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}

{% buttons %}
    <button type="submit" class="btn btn-primary">Check Answer</button>
{% endbuttons %}
</form>

</div>
{% endblock %}

qwizkoolweb/quiz/templates/question_results.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}
<div class="container">

<p><h5>{{ question.question_text }}</h5></p>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} </li>
{% endfor %}
</ul>

{% if passed %}
    {% if result_message %}<p class="text-success"><strong>{{ result_message }}</strong></p>{% endif %}
{% else %}
    {% if result_message %}<p class="text-danger"><strong>{{ result_message }}</strong></p>{% endif %}
{% endif %}

{% if next_question %}
<form action="{% url 'quiz:question' question.quiz.id next_question.id %}" method="get">
    {% csrf_token %}
    {% buttons %}
    <button type="submit" class="btn btn-primary">Next Question</button>
    {% endbuttons %}    
    
</form>
{% endif %}

<form action="{% url 'quiz:quiz_results' question.quiz.id %}" method="get">
    {% csrf_token %}
    {% buttons %}
    <button type="submit" class="btn btn-primary">End Quiz</button>
    {% endbuttons %}    
</form>

</div>
{% endblock %}

qwizkoolweb/quiz/templates/quiz_detail.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}
<div class="container">

<p><h4>{{ quiz.title_text }}</h4></p>
<h6>{{ quiz.description_text }}</h6>

<form action="{% url 'quiz:question' quiz.id question.id %}" method="get">
{% csrf_token %}
{% buttons %}
<button type="submit" class="btn btn-primary">Start Quiz</button>
{% endbuttons %}    
</form>

</div>
{% endblock %}

qwizkoolweb/quiz/templates/quiz_results.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}
<div class="container">

<p><h4>{{ quiz.title_text }} Quiz Results</h4></p>

<h6><p class="text-dark">Total Questions: {{ total }}</p></h6>
<h6><p class="text-dark">Number attempted: {{ attempted }}</p></h6>
<h6><p class="text-success">Number Correct: {{ correct }}</p></h6>
<h6><p class="text-danger">Number Wrong: {{ wrong }}</p></h6>

<form action="{% url 'quiz:index' %}" method="get">
    {% csrf_token %}
    {% buttons %}
        <button type="submit" class="btn btn-primary">Go Home</button>
    {% endbuttons %}    
</form>

</div>
{% endblock %}

qwizkoolweb/quiz/templates/sidebar.html
{% block sidebar %}

<style>
        .card{
            box-shadow: 0 16px 48px #E3E7EB;
        }

</style>

<!-- Sidebar Widgets Column -->
<div class="col-md-4 float-right ">
<div class="card my-4">
        <h5 class="card-header">About Us</h5>
    <div class="card-body">
        <p class="card-text"> This smart quiz generator is made on the top of AI and NLP</p>
        <a href="https://en.wikipedia.org/wiki/Natural_language_processing"
        class="btn btn-primary">Learn more!</a>
    </div>
</div>
</div>

{% endblock sidebar %}